version: 2
jobs:
  build:
    environment:
      - FLUTTER_VERSION: 1.6.3
    docker:
      - image: circleci/elixir:1.7.3

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # specify any bash command here prefixed with `run: `
      - run: docker build --build-arg FLUTTER_VERSION=${FLUTTER_VERSION} -t larskj/flutter:${FLUTTER_VERSION} .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PWD
      - run: docker push larskj/flutter:${FLUTTER_VERSION}
