version: 2
jobs:
  build:
    docker:
    - image: circleci/elixir:1.7.3

    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true

    # specify any bash command here prefixed with `run: `
    - run: docker build -t larskj/flutter:0.11.12 .
    - run: docker login -u $DOCKER_USER -p $DOCKER_PWD
    - run: docker push larskj/flutter:0.11.12
